# Generated by Django 5.2.4 on 2025-08-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('platform', models.CharField(choices=[('Netflix', 'Netflix'), ('HBO Max', 'HBO Max'), ('Disney+', 'Disney+'), ('Amazon Prime Video', 'Amazon Prime Video'), ('Spotify', 'Spotify'), ('YouTube Premium', 'YouTube Premium'), ('Other', 'Otro')], max_length=50, verbose_name='Plataforma')),
                ('details', models.TextField(verbose_name='Detalles de la Cuenta (Usuario/Contraseña/Notas)')),
                ('expiration_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cuenta de Streaming',
                'verbose_name_plural': 'Cuentas de Streaming',
                'ordering': ['expiration_date'],
            },
        ),
    ]
